### PR TITLE
Add ``environment_variables`` to best practice order list.

### PR DESCRIPTION
**Pull request by jmchilton**

### CODE REVIEW

**Comment by nsoranzo** [comment]
Never seen this element, is it in use somewhere?

**Comment by jmchilton** [comment]
Documented here - https://github.com/galaxyproject/galaxy/pull/395. It will be added to the planemo docs in some form shortly.

**Comment by nsoranzo** [comment]
Thanks @jmchilton, completely forgot about it. Strange it has not been used in tools-iuc or tools-devteam yet.

**Comment by bgruening** [comment]
Thanks!

**Pull request merged**
