### PR TITLE
Update tool_xml.rst about Datatypes

### PR DESCRIPTION
**Pull request by remimarenco**
Hi!

I am working on adding my datatype into my TS installation, along with my tool, and I saw that this part was fulfilled with TODO. I am adding the link to the Galaxy Wiki so people will be able to know how to do it without planemo :).

### CODE REVIEW

**Comment by nsoranzo** [comment]
I think that the only current IUC best practice about datatypes is "push them into galaxy repository".

**Comment by bgruening** [comment]
Agree with @nsoranzo. We decided together with the Galaxy team that for now we recommend to get datatype definitions into Galaxy core. Maybe you can add such a sentence as well?

**Comment by remimarenco** [comment]
Thanks, I have done the changes :)

**Comment by bgruening** [comment]
This is a good improvement. Thanks @remimarenco!
In a later PR you could change it to "datatype/datatypes".
Maybe add a link to already existing datatypes and a hint that you can create a python class or simply subclass a already existing one?

**Pull request merged**
