### PR TITLE
Rewrite best practices to encourage tabs

### LINKED ISSUE #73: Tabs should be permitted, maybe even mandatory.
They're better for accessibility:

- [Prettier is considering changing to that by default](https://twitter.com/rich_harris/status/1541761871585464323)
- [their arguments for them](https://github.com/prettier/prettier/issues/7475#issuecomment-668544890)
- https://adamtuttle.codes/blog/2021/tabs-vs-spaces-its-an-accessibility-issue/
- https://dev.to/alexandersandberg/why-we-should-default-to-tabs-instead-of-spaces-for-an-accessible-first-environment-101f

I've never understood IUC's _demand_ for them (they're "best practice" but somehow also 100% mandatory), and I think we should change this. Clients can set tabs to any width they personally prefer, you can have 2 or 8 or 4, and folks that want them for accessibility reasons will finally have them.

(sorry to restart this old argument.)

### PR DESCRIPTION
**Pull request by hexylena**
While still allowing spaces, and just promoting consistency. Fixes #73

### CODE REVIEW

**Comment by nsoranzo** [comment]
I am heavily conflicted on this. I fully support the goal of improving accessibility, but I don't know enough about the available tools to say this is the best solution.
I think we should explicitly exclude Python scripts from this recommendation, given that PEP-8, black, standard library and all major Python projects (including the Galaxy ecosystem) all use 4-space indentation. Or specify it applies only to the XML files.

**Comment by hexylena** [comment]
Yes, agreed. As written, both of these changes only affects tool XML related sections. 

One is specifically in the `docs/best_practices/tool_xml.rst`, while the other is the last bullet of a heading `Creating the Tool Wrapper (XML File)`

**Comment by peterjc** [comment]
As @hexylena  points out this is under an XML section, but would making the new bullet point starting "_Use tabs for indentation_" read "_Use tabs for XML indentation_" help @nsoranzo?

**Comment by nsoranzo** [comment]
> Yes, agreed. As written, both of these changes only affects tool XML related sections.
> 
> One is specifically in the `docs/best_practices/tool_xml.rst`, while the other is the last bullet of a heading `Creating the Tool Wrapper (XML File)`

The `Coding Style` section in `docs/best_practices/tool_xml.rst` talks also about Python code style later on, so I think it could be confusing there.

"Tabs for XML indentation" would work for me!

**Comment by hexylena** [comment]
Fixed, per y'all's suggestion :) @nsoranzo @peterjc

**Comment by bgruening** [comment]
> "Tabs for XML indentation"

This means only the XML tags inside the XML files, so not the cheetah and the rst section?

**Comment by peterjc** [comment]
Good question, can the cheetah and RST be done with either tabs or space indentation from a technical point of view?

The RST specification says at https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#whitespace that:

> Spaces are recommended for [indentation](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#indentation), but tabs may also be used.

It may be pragmatic to recommend tabs only for the XML tags, and spaces for embedded RST?

**Comment by hexylena** [comment]
It's been 3 weeks, any objections to merging? If not?

**Comment by hexylena** [comment]
I'd like to see it recommended for the cheetah sections as well (that's always worked fine) and since by their documentation it works fine for rST, I'd argue we should provide a more consistent guidance, namely:

- tabs are suggested for all parts, the XML, the cheetah (works), and the rST (supported!)
- and if you are consistent, you are permitted to use spaces for all three
- we do not recommend mixing tabs and spaces in the file, consistency is encouraged

**Comment by bgruening** [comment]
I think we are pretty much a Python community (cheetah, rst ...) and they recommend spaces instead of tabs. I don't see why we should recommend tabs here. 

Maybe we can remove the current recommendation and just not recommend anything, just staying stay consistent. Overall the important part is that people can use what they can deal with best.

**Comment by hexylena** [comment]
> I don't see why we should recommend tabs here.

This discussion in a large part was started by wanting to make things more accessible to everyone, and more welcoming for those users, hence making that the recommendation, but allowing it open to personal choice.

> and just not recommend anything, just staying stay consistent

As it stands, with the text as it is now, any contributor would be free to stick with spaces. But by having the recommendation we can at least push for some small tiny amount of slow change in a positive direction.

The only time having this "recommendation" would be bad, is if a reviewer decided to ignore that it is a "recommendation" and make it mandatory for a contributor.

**Comment by hexylena** [comment]
given the lack of motion on this, I will close it.

**Pull request closed without merging**
