### PR TITLE
Fix checklist for tool-data

### PR DESCRIPTION
**Pull request by mblue9**
Suggesting these changes as it was not clear to me from this doc that I also needed additional files for testing a tool with a data table with Planemo.

### CODE REVIEW

**Comment by peterjc** [comment]
This information is worth including, but I would word it differently. To start with, you should be providing ``tool-data/effectiveT3.loc.sample``  and ``tool_data_table_conf.xml.sample`` anyway, regardless of the tests. Perhaps that should be moved above the section on tests?

Next, I would clarify that ``test-data/data_table_name.loc`` is only needed if ``tool-data/data_table_name.loc.sample`` is not suitable for the tests.

Likewise I suspect ``tool_data_table_conf.xml.test`` is only needed if ``tool_data_table_conf.xml.sample`` is not suitable for the tests (in fact, I don't recall ever using it).

**Comment by nsoranzo** [comment]
@peterjc In general `tool-data/data_table_name.loc.sample` and `tool_data_table_conf.xml.sample` should contain only comments, no?
@mblue9 I'd also add a link to an example repo, e.g. https://github.com/galaxyproject/tools-devteam/tree/master/tools/bowtie_wrappers

**Comment by peterjc** [comment]
@nsoranzo if the tool is bundled with a default set of databases or configurations, then it makes sense to include entries in the sample configuration - e.g. https://github.com/peterjc/pico_galaxy/tree/master/tools/effectiveT3 ships with https://github.com/peterjc/pico_galaxy/blob/master/tool-data/effectiveT3.loc.sample

**Comment by nsoranzo** [comment]
I said "in general", I think this is quite a specific case, all data tables for genome indexes and/or administered with a data manager come with an empty sample file.

**Comment by peterjc** [comment]
You're probably right, I've only relatively rarely used ``*.loc`` files.

I still think we should discuss the data tables before the tests though, with the change as is the data tables section becomes part of the paragraph on tests.

**Comment by mblue9** [comment]
Hi @peterjc and @nsoranzo 

Thanks for the comments!

I'm made some changes and, am not sure if I've got it right on what I should include (please let me know!), but based on your comments I've 

 - adjusted the text and positioning of the tool-data mentions and testing of tool-data (I thought this was a combined tool-data/testing section because of how it was spaced :) so I've also removed the extra blank lines)

- added in a link to the bowtie wrapper, and Nicola, I've used your info from here http://dev.list.galaxyproject.org/planemo-test-with-lt-options-from-data-table-gt-td4670119.html

because that post was how I finally cracked how to get the data table testing to work! That was the trickiest part of the tool testing to get working and I think it would be great if that info was easier to find.

What do you think? I'm happy to edit more?

**Comment by peterjc** [comment]
You should put the double-back-tick RST markup around the path names and XML snippet, but I think that is a big improvement.

**Comment by mblue9** [comment]
Thanks @peterjc!

I've added the RST markup and also some links, see what you think. 

If you (or anyone) think I should edit more just let me know!

**Comment by peterjc** [comment]
Good work - what do you think @nsoranzo - ready to merge?

**Comment by nsoranzo** [comment]
Thanks a lot @mblue9!

**Pull request merged**
